title: Helio Machado
author: Helio Machado
blog_title: /var/log/0x2b3bfa0

googleplus:
  - +Helio Machado
  - https://plus.google.com/+HelioMachadoM

github: 0x2b3bfa0

email: MHgyYjNiZmEwK2NvbnRhY3RAZ29vZ2xlbWFpbC5jb20= # Base64 descrambled at runtime. I hate spam.

description: >
  A place to log my life with different verbosity levels.

show_excerpts: enabled

timezone: Atlantic/Canary
encoding: utf-8

baseurl: ""
url: "https://crushedice2000.github.io"

# disqus:
#   shortname: 0x2b3bfa0 # TODO create a new disqus account

permalink: pretty

markdown: kramdown
theme: minima

# collections:
#   - portfolio

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
