title: Helio Machado
author: Helio Machado
blog_title: /var/log/crushedice2000

googleplus:
  - +Helio Machado
  - https://plus.google.com/+HelioMachadoM

github: crushedice2000

email: Y3J1c2hlZGljZTIwMDBAZ21haWwuY29t # Base64 descrambled at runtime. I hate spam.

description: >
  A place to log my life with different verbosity levels.

show_excerpts: enabled

timezone: Atlantic/Canary
encoding: utf-8

baseurl: ""
url: "https://crushedice2000.github.io"

disqus:
  shortname: crushedice2000

permalink: pretty

markdown: kramdown
theme: minima

collections:
  - portfolio

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
